name: ctx-secrets
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Usar secreto en un comando
        env:
          TOKEN: ${{ secrets.API_KEY }}
        run: |
          echo "Tengo un token secreto y no se mostrará su valor ${{ secrets.API_KEY }}"
          # ejemplo real: curl -H "Authorization: Bearer $TOKEN" https://api.ejemplo.com/ping
