name: Envs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "ENTORNO=${{ vars.ENTORNO }}"
      - run: curl -H "Auth: Bearer ${{ secrets.API_KEY }}" https://api.ejemplo.com
